POST http://localhost:3001/api/codes
Content-Type: application/json
x-make-secret: patronplay89uD7c7DSEZqQCL

{
    "from":"noreply@tm.openai.com",
    "to":"pdplay10@gmail.com",
    "date": "Tue, 21 Aug 2025 23:21:58 GMT",
    "subject":"Your ChatGPT password reset code is 150062",
    "body":"Enter this temporary verification code to continue:\n\n586569\n\nPlease ignore this email if you weren’t trying to reset your password.\n\n\nBest,\nThe ChatGPT team"
}
